// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/llm_proto/llm_inference.proto

package llm_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_internal_llm_proto_llm_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_llm_proto_llm_inference_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_internal_llm_proto_llm_inference_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_llm_proto_llm_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_internal_llm_proto_llm_inference_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_internal_llm_proto_llm_inference_proto protoreflect.FileDescriptor

const file_internal_llm_proto_llm_inference_proto_rawDesc = "" +
	"\n" +
	"&internal/llm_proto/llm_inference.proto\x12\tllm_proto\"'\n" +
	"\rPromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"&\n" +
	"\x10EmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding2\xeb\x01\n" +
	"\fLLMInference\x12H\n" +
	"\x10GenerateResponse\x12\x18.llm_proto.PromptRequest\x1a\x18.llm_proto.TokenResponse0\x01\x12I\n" +
	"\fGetEmbedding\x12\x1b.llm_proto.EmbeddingRequest\x1a\x1c.llm_proto.EmbeddingResponse\x12F\n" +
	"\x10GetUnaryResponse\x12\x18.llm_proto.PromptRequest\x1a\x18.llm_proto.TokenResponseB<Z:github.com/arunima10a/llm-collab-system/internal/llm_protob\x06proto3"

var (
	file_internal_llm_proto_llm_inference_proto_rawDescOnce sync.Once
	file_internal_llm_proto_llm_inference_proto_rawDescData []byte
)

func file_internal_llm_proto_llm_inference_proto_rawDescGZIP() []byte {
	file_internal_llm_proto_llm_inference_proto_rawDescOnce.Do(func() {
		file_internal_llm_proto_llm_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_llm_proto_llm_inference_proto_rawDesc), len(file_internal_llm_proto_llm_inference_proto_rawDesc)))
	})
	return file_internal_llm_proto_llm_inference_proto_rawDescData
}

var file_internal_llm_proto_llm_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_llm_proto_llm_inference_proto_goTypes = []any{
	(*PromptRequest)(nil),     // 0: llm_proto.PromptRequest
	(*TokenResponse)(nil),     // 1: llm_proto.TokenResponse
	(*EmbeddingRequest)(nil),  // 2: llm_proto.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 3: llm_proto.EmbeddingResponse
}
var file_internal_llm_proto_llm_inference_proto_depIdxs = []int32{
	0, // 0: llm_proto.LLMInference.GenerateResponse:input_type -> llm_proto.PromptRequest
	2, // 1: llm_proto.LLMInference.GetEmbedding:input_type -> llm_proto.EmbeddingRequest
	0, // 2: llm_proto.LLMInference.GetUnaryResponse:input_type -> llm_proto.PromptRequest
	1, // 3: llm_proto.LLMInference.GenerateResponse:output_type -> llm_proto.TokenResponse
	3, // 4: llm_proto.LLMInference.GetEmbedding:output_type -> llm_proto.EmbeddingResponse
	1, // 5: llm_proto.LLMInference.GetUnaryResponse:output_type -> llm_proto.TokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_llm_proto_llm_inference_proto_init() }
func file_internal_llm_proto_llm_inference_proto_init() {
	if File_internal_llm_proto_llm_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_llm_proto_llm_inference_proto_rawDesc), len(file_internal_llm_proto_llm_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_llm_proto_llm_inference_proto_goTypes,
		DependencyIndexes: file_internal_llm_proto_llm_inference_proto_depIdxs,
		MessageInfos:      file_internal_llm_proto_llm_inference_proto_msgTypes,
	}.Build()
	File_internal_llm_proto_llm_inference_proto = out.File
	file_internal_llm_proto_llm_inference_proto_goTypes = nil
	file_internal_llm_proto_llm_inference_proto_depIdxs = nil
}
