# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from internal.llm_proto import llm_inference_pb2 as internal_dot_llm__proto_dot_llm__inference__pb2


class LLMInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_stream(
                '/llm_proto.LLMInference/GenerateResponse',
                request_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.SerializeToString,
                response_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.FromString,
                )
        self.GetEmbedding = channel.unary_unary(
                '/llm_proto.LLMInference/GetEmbedding',
                request_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingResponse.FromString,
                )
        self.GetUnaryResponse = channel.unary_unary(
                '/llm_proto.LLMInference/GetUnaryResponse',
                request_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.SerializeToString,
                response_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.FromString,
                )


class LLMInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnaryResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.FromString,
                    response_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingRequest.FromString,
                    response_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GetUnaryResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnaryResponse,
                    request_deserializer=internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.FromString,
                    response_serializer=internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm_proto.LLMInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLMInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/llm_proto.LLMInference/GenerateResponse',
            internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.SerializeToString,
            internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm_proto.LLMInference/GetEmbedding',
            internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingRequest.SerializeToString,
            internal_dot_llm__proto_dot_llm__inference__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnaryResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm_proto.LLMInference/GetUnaryResponse',
            internal_dot_llm__proto_dot_llm__inference__pb2.PromptRequest.SerializeToString,
            internal_dot_llm__proto_dot_llm__inference__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
