# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/llm_proto/llm_inference.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&internal/llm_proto/llm_inference.proto\x12\tllm_proto\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\xeb\x01\n\x0cLLMInference\x12H\n\x10GenerateResponse\x12\x18.llm_proto.PromptRequest\x1a\x18.llm_proto.TokenResponse0\x01\x12I\n\x0cGetEmbedding\x12\x1b.llm_proto.EmbeddingRequest\x1a\x1c.llm_proto.EmbeddingResponse\x12\x46\n\x10GetUnaryResponse\x12\x18.llm_proto.PromptRequest\x1a\x18.llm_proto.TokenResponseB<Z:github.com/arunima10a/llm-collab-system/internal/llm_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal.llm_proto.llm_inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/arunima10a/llm-collab-system/internal/llm_proto'
  _globals['_PROMPTREQUEST']._serialized_start=53
  _globals['_PROMPTREQUEST']._serialized_end=84
  _globals['_TOKENRESPONSE']._serialized_start=86
  _globals['_TOKENRESPONSE']._serialized_end=116
  _globals['_EMBEDDINGREQUEST']._serialized_start=118
  _globals['_EMBEDDINGREQUEST']._serialized_end=150
  _globals['_EMBEDDINGRESPONSE']._serialized_start=152
  _globals['_EMBEDDINGRESPONSE']._serialized_end=190
  _globals['_LLMINFERENCE']._serialized_start=193
  _globals['_LLMINFERENCE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
