// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/llm_proto/llm_inference.proto

package llm_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMInference_GenerateResponse_FullMethodName = "/llm_proto.LLMInference/GenerateResponse"
	LLMInference_GetEmbedding_FullMethodName     = "/llm_proto.LLMInference/GetEmbedding"
	LLMInference_GetUnaryResponse_FullMethodName = "/llm_proto.LLMInference/GetUnaryResponse"
)

// LLMInferenceClient is the client API for LLMInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMInferenceClient interface {
	GenerateResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenResponse], error)
	GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	GetUnaryResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type lLMInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMInferenceClient(cc grpc.ClientConnInterface) LLMInferenceClient {
	return &lLMInferenceClient{cc}
}

func (c *lLMInferenceClient) GenerateResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMInference_ServiceDesc.Streams[0], LLMInference_GenerateResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PromptRequest, TokenResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMInference_GenerateResponseClient = grpc.ServerStreamingClient[TokenResponse]

func (c *lLMInferenceClient) GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, LLMInference_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMInferenceClient) GetUnaryResponse(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, LLMInference_GetUnaryResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMInferenceServer is the server API for LLMInference service.
// All implementations must embed UnimplementedLLMInferenceServer
// for forward compatibility.
type LLMInferenceServer interface {
	GenerateResponse(*PromptRequest, grpc.ServerStreamingServer[TokenResponse]) error
	GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	GetUnaryResponse(context.Context, *PromptRequest) (*TokenResponse, error)
	mustEmbedUnimplementedLLMInferenceServer()
}

// UnimplementedLLMInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMInferenceServer struct{}

func (UnimplementedLLMInferenceServer) GenerateResponse(*PromptRequest, grpc.ServerStreamingServer[TokenResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateResponse not implemented")
}
func (UnimplementedLLMInferenceServer) GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedLLMInferenceServer) GetUnaryResponse(context.Context, *PromptRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnaryResponse not implemented")
}
func (UnimplementedLLMInferenceServer) mustEmbedUnimplementedLLMInferenceServer() {}
func (UnimplementedLLMInferenceServer) testEmbeddedByValue()                      {}

// UnsafeLLMInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMInferenceServer will
// result in compilation errors.
type UnsafeLLMInferenceServer interface {
	mustEmbedUnimplementedLLMInferenceServer()
}

func RegisterLLMInferenceServer(s grpc.ServiceRegistrar, srv LLMInferenceServer) {
	// If the following call panics, it indicates UnimplementedLLMInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMInference_ServiceDesc, srv)
}

func _LLMInference_GenerateResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PromptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMInferenceServer).GenerateResponse(m, &grpc.GenericServerStream[PromptRequest, TokenResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMInference_GenerateResponseServer = grpc.ServerStreamingServer[TokenResponse]

func _LLMInference_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMInferenceServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMInference_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMInferenceServer).GetEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMInference_GetUnaryResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMInferenceServer).GetUnaryResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMInference_GetUnaryResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMInferenceServer).GetUnaryResponse(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMInference_ServiceDesc is the grpc.ServiceDesc for LLMInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm_proto.LLMInference",
	HandlerType: (*LLMInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmbedding",
			Handler:    _LLMInference_GetEmbedding_Handler,
		},
		{
			MethodName: "GetUnaryResponse",
			Handler:    _LLMInference_GetUnaryResponse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateResponse",
			Handler:       _LLMInference_GenerateResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/llm_proto/llm_inference.proto",
}
